Svelte 5 Only
kbrgl/svelte-french-toast pull request #82
Opened 2024-10-04 04:41 UTC by anatoliy-t7

### The package will work with  Svelte 5 Only

- migrate to Svelte 5 syntaxis
- update all packages
- small fix

2024-10-09 09:32 UTC, mustafa0x commented
@anatoliy-t7 nice work! but i think the last commit should be deleted.

2024-10-09 10:23 UTC, anatoliy-t7 commented
> @anatoliy-t7 nice work! but i think the last commit should be deleted.

I don't want to get credits from work that @kbrgl did. I just rewrote it a little.

2024-10-24 02:48 UTC, okuruu approved these changes
LGTM!

2024-10-25 23:58 UTC, thebjorn commented on .gitignore
> -/dist
Why have you included the dist folder?

2024-10-25 23:58 UTC, thebjorn commented on bun.lockb
Please don't change the build tools used by the author or include 134K binary blobs (remember the xz backdoor supply chain attack).

2024-10-25 23:58 UTC, thebjorn commented on package.json
> -	"version": "1.2.0",
This is a backwards incompatible change, so the version needs to be 2.0.0.

2024-10-25 23:58 UTC, thebjorn commented on package.json
> +		"svelte": "^5.0.0-next.1"
`"^5"` or `"^5.0.0"` (you want to select any 5.x.x version)

2024-10-25 23:58 UTC, thebjorn commented on package.json
> +		"@sveltejs/vite-plugin-svelte": "^4.0.0-next.7",
`"^4.0.0"`

2024-10-25 23:58 UTC, thebjorn commented on package.json
> +		"svelte": "^5.0.0-next.260",
`"^5.0.0"`

2024-10-30 10:44 UTC, writeDavid commented
@kbrgl what do you think of these changes? Now that Svelte 5 is officially out, it makes sense to ensure projects can upgrade and still use this project.

2024-10-30 11:19 UTC, mustafa0x commented
should use pnpm-lock instead of adding package-lock

2024-10-30 23:30 UTC, enesbala5 commented
Can we please get an update on this? I need to use the library for a project - it seems like everything is ready at this point, right?

2024-11-02 14:03 UTC, babakfp commented
I published this https://github.com/babakfp/svelte-hot-french-toast if anyone interested. Uses Svelte 5 and runes.

2024-11-17 18:28 UTC, DollarAkshay approved these changes
LGTM

2024-12-10 09:51 UTC, kbrgl approved these changes

2024-12-10 10:05 UTC, kbrgl requested changes

2024-12-10 10:25 UTC, anatoliy-t7 commented on package-lock.json
Done

2024-12-27 06:34 UTC, bn-l commented
Hey any updates?

2025-02-22 06:07 UTC, ezShroom commented
well isn't this ready to go now?

2025-02-22 06:31 UTC, kbrgl approved these changes

2025-02-22 06:32 UTC, kbrgl requested changes
going to merge this on my branch

2025-02-22 07:06 UTC, kbrgl commented on src/lib/components/ToastBar.svelte
> +	style={toast.style}
Does this mean the style passed to this component doesn't get applied?

2025-02-22 09:54 UTC, kbrgl commented
Closed in favor of #89.

2025-02-22 09:55 UTC, closed without merging